version: '3'

services:
  client:
    container_name: dug-search-client
    build:
      args:
        NODE_ENV: production
        REACT_APP_DUG_URL: $DUG_URL 
     context: .
      dockerfile: Dockerfile-prod
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:8080
    restart: always
